 artifacts_root: artifacts

 data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/MamoonaRamzan/Datasets/raw/refs/heads/main/Brain%20tumor%20Dataset.zip
  local_data_files: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion